name: Build Lazar Severin Bumbaru websockets
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/websockets.yml
      - .shared/**
      - websockets/**
  workflow_dispatch:
jobs:
  build_severin_bumbaru_2023_doker_img:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        node-version: [18.x]
        name: [docker-severin-bumbaru-2023-websockets]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: sudo docker build . -f ./websockets/cfr/Dockerfile -t monsieurlazar/docker-severin-bumbaru-2023-websockets
    - name: Login to Docker Hub
      env:
        DOCKER_KEY: ${{ secrets.DOCKER_KEY }}
      run: sudo docker login --username monsieurlazar --password $DOCKER_KEY
    - name: Push
      run: sudo docker push monsieurlazar/docker-severin-bumbaru-2023-websockets
  update_severin_bumbaru_2023_doker_img:
    name: Update
    needs: "build_severin_bumbaru_2023_doker_img"
    runs-on: self-hosted
    steps:
    - run: sudo docker stop docker-severin-bumbaru-2023-websockets || true && sudo docker rm docker-severin-bumbaru-2023-websockets || true
    - run: sudo docker rmi monsieurlazar/docker-severin-bumbaru-2023-websockets || true
    - run: sudo docker run --network lazar-network -d --name docker-severin-bumbaru-2023-websockets monsieurlazar/docker-severin-bumbaru-2023-websockets